### ✅ Successful registration
POST http://localhost:3000/auth/register
Content-Type: application/json
Accept: application/json

{
  "name": "Muhammad Sohaib",
  "username": "SohaibMalik432",
  "email": "mohammadsohaib432@gmail.com",
  "password": "Sohaib@123"
}
